# Generated by Django 6.0.7 on 2026-08-01 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('REGISTER', 'Registration'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PROFILE_UPDATE', 'Profile updated'), ('ARTICLE_READ', 'Article read'), ('VIDEO_WATCH', 'Video watched'), ('LIVE_JOIN', 'Live joined'), ('COURSE_VIEW', 'Course viewed'), ('COURSE_SESSION_VIEW', 'Course session viewed'), ('CREATE', 'Content created'), ('UPDATE', 'Content updated'), ('DELETE', 'Content deleted'), ('SOCIAL', 'Social activity'), ('SECURITY', 'Security activity')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('target_type', models.CharField(blank=True, max_length=80)),
                ('target_id', models.CharField(blank=True, max_length=80)),
                ('target_url', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='activity_us_user_id_b05f78_idx')],
            },
        ),
    ]
