# Generated by Django 6.0.7 on 2026-08-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('REGISTER', 'Registration'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PROFILE_UPDATE', 'Profile updated'), ('ARTICLE_READ', 'Article read'), ('VIDEO_WATCH', 'Video watched'), ('LIVE_JOIN', 'Live joined'), ('COURSE_VIEW', 'Course viewed'), ('COURSE_SESSION_VIEW', 'Course session viewed'), ('CREATE', 'Content created'), ('UPDATE', 'Content updated'), ('DELETE', 'Content deleted'), ('SOCIAL', 'Social activity'), ('SECURITY', 'Security activity'), ('PERSONALITY_TEST_COMPLETED', 'Personality test completed')], max_length=30),
        ),
    ]
