# Generated by Django 6.0.7 on 2026-07-25 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_platformrole_user_custom_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], max_length=30)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('postal_code', models.CharField(blank=True, max_length=30)),
                ('marital_status', models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], max_length=30)),
                ('education_level', models.CharField(blank=True, choices=[('HIGH_SCHOOL', 'High school'), ('ASSOCIATE', 'Associate'), ('BACHELOR', 'Bachelor'), ('MASTER', 'Master'), ('DOCTORATE', 'Doctorate'), ('OTHER', 'Other')], max_length=30)),
                ('occupation', models.CharField(blank=True, max_length=150)),
                ('job_title', models.CharField(blank=True, max_length=150)),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('monthly_income_range', models.CharField(blank=True, choices=[('NO_INCOME', 'No income'), ('UNDER_500', 'Under 500'), ('500_1000', '500 to 1,000'), ('1000_3000', '1,000 to 3,000'), ('3000_5000', '3,000 to 5,000'), ('5000_10000', '5,000 to 10,000'), ('OVER_10000', 'Over 10,000'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], max_length=30)),
                ('income_currency', models.CharField(blank=True, max_length=10)),
                ('income_sources', models.JSONField(blank=True, default=list)),
                ('financial_dependents', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('trading_experience_years', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('risk_tolerance', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=20)),
                ('investment_goal', models.TextField(blank=True)),
                ('preferred_markets', models.JSONField(blank=True, default=list)),
                ('trading_frequency', models.CharField(blank=True, choices=[('NEVER', 'Never'), ('RARELY', 'Rarely'), ('WEEKLY', 'Weekly'), ('DAILY', 'Daily'), ('MULTIPLE_DAILY', 'Multiple times daily')], max_length=30)),
                ('daily_free_time_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('learning_hours_weekly', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('preferred_learning_time', models.CharField(blank=True, choices=[('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon'), ('EVENING', 'Evening'), ('NIGHT', 'Night'), ('FLEXIBLE', 'Flexible')], max_length=20)),
                ('exercise_days_per_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sleep_hours_average', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('habits', models.JSONField(blank=True, default=dict)),
                ('onboarding_answers', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('exercise_days_per_week__isnull', True), ('exercise_days_per_week__lte', 7), _connector='OR'), name='profile_exercise_days_max_7'), models.CheckConstraint(condition=models.Q(('sleep_hours_average__isnull', True), ('sleep_hours_average__lte', 24), _connector='OR'), name='profile_sleep_hours_max_24'), models.CheckConstraint(condition=models.Q(('daily_free_time_minutes__isnull', True), ('daily_free_time_minutes__lte', 1440), _connector='OR'), name='profile_free_time_max_1440'), models.CheckConstraint(condition=models.Q(('learning_hours_weekly__isnull', True), ('learning_hours_weekly__lte', 168), _connector='OR'), name='profile_learning_hours_max_168')],
            },
        ),
    ]
