# Generated by Django 6.0.7 on 2026-08-03 05:02

import common.phone
from django.db import migrations, models


def normalize_existing_phones(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    planned = {}
    for user in User.objects.exclude(phone__isnull=True).exclude(phone="").only("id", "phone"):
        try:
            normalized = common.phone.normalize_iran_phone(user.phone)
        except Exception as exc:
            raise RuntimeError(f"Invalid legacy phone on user id={user.id}; fix it before migration.") from exc
        if normalized in planned and planned[normalized] != user.id:
            raise RuntimeError(
                f"Duplicate canonical phone detected for user ids {planned[normalized]} and {user.id}; migration stopped without deleting data."
            )
        planned[normalized] = user.id
    for normalized, user_id in planned.items():
        User.objects.filter(pk=user_id).update(phone=normalized)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_badge_securitysettings_userbadge_userdevice'),
    ]

    operations = [
        migrations.RunPython(normalize_existing_phones, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[common.phone.validate_iran_phone]),
        ),
        migrations.CreateModel(
            name='OTPChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=11)),
                ('code_digest', models.CharField(max_length=64)),
                ('salt', models.CharField(max_length=64)),
                ('request_ip', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', '-created_at'], name='accounts_ot_phone_b43396_idx')],
            },
        ),
    ]
