# Generated by Django 6.0.7 on 2026-08-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_brokerconnection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitysettings',
            name='session_lifetime_days',
            field=models.PositiveSmallIntegerField(default=30),
        ),
    ]
