# Generated by Django 6.0.7 on 2026-08-24 08:49

from django.db import migrations, models


def normalize_profiles_and_support(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    Profile = apps.get_model("accounts", "UserProfile")
    User.objects.filter(username__iexact="support").update(
        role="SUPPORT", custom_role=None, is_staff=False, is_superuser=False
    )
    income_map = {
        "UNDER_500": "UNDER_10M_IRT", "500_1000": "10M_30M_IRT",
        "1000_3000": "30M_60M_IRT", "3000_5000": "60M_100M_IRT",
        "5000_10000": "OVER_100M_IRT", "OVER_10000": "OVER_100M_IRT",
    }
    for profile in Profile.objects.all().iterator():
        profile.country = (profile.country or "IR").strip().upper()[:2] or "IR"
        profile.income_currency = "IRT"
        profile.monthly_income_range = income_map.get(profile.monthly_income_range, profile.monthly_income_range)
        profile.save(update_fields=["country", "income_currency", "monthly_income_range"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_securitysettings_session_lifetime_days'),
    ]

    operations = [
        migrations.RunPython(normalize_profiles_and_support, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('TRADER', 'Trader'), ('EMPLOYEE', 'Employee'), ('SUPPORT', 'Support'), ('USER', 'User')], default='USER', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(default='IR', max_length=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='income_currency',
            field=models.CharField(default='IRT', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='monthly_income_range',
            field=models.CharField(blank=True, choices=[('NO_INCOME', 'No income'), ('UNDER_10M_IRT', 'Under 10M IRT'), ('10M_30M_IRT', '10M to 30M IRT'), ('30M_60M_IRT', '30M to 60M IRT'), ('60M_100M_IRT', '60M to 100M IRT'), ('OVER_100M_IRT', 'Over 100M IRT'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], max_length=30),
        ),
    ]
