# Generated by Django 6.0.7 on 2026-08-24 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_role_alter_userprofile_country_and_more'),
        ('wallet', '0002_ledgertransaction_paymentprovider_upgradeplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgraderequest',
            name='hold_ledger_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='upgrade_holds', to='wallet.ledgertransaction'),
        ),
        migrations.AddField(
            model_name='upgraderequest',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wallet.upgradeplan'),
        ),
        migrations.AddField(
            model_name='upgraderequest',
            name='price_snapshot_irt',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
