# Generated by Django 6.0.7 on 2026-08-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_upgraderequest_hold_ledger_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='monthly_income_range',
            field=models.CharField(blank=True, choices=[('NO_INCOME', 'No income'), ('UNDER_10M_IRT', 'Under 10M IRT'), ('10M_30M_IRT', '10M to 30M IRT'), ('30M_60M_IRT', '30M to 60M IRT'), ('60M_100M_IRT', '60M to 100M IRT'), ('OVER_100M_IRT', 'Over 100M IRT'), ('UNDER_500', 'Legacy: under 500'), ('500_1000', 'Legacy: 500 to 1,000'), ('1000_3000', 'Legacy: 1,000 to 3,000'), ('3000_5000', 'Legacy: 3,000 to 5,000'), ('5000_10000', 'Legacy: 5,000 to 10,000'), ('OVER_10000', 'Legacy: over 10,000'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], max_length=30),
        ),
    ]
