# Generated by Django 6.0.7 on 2026-08-28 07:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_userprofile_monthly_income_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialPersonalityAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('personality_type', models.CharField(choices=[('WEALTH_ARCHITECT', 'معمار ثروت'), ('CAPITAL_GUARDIAN', 'نگهبان سرمایه'), ('OPPORTUNITY_HUNTER', 'شکارچی فرصت'), ('DISCIPLINED_NAVIGATOR', 'ناوبر منضبط'), ('MARKET_EXPLORER', 'کاوشگر بازار')], max_length=30)),
                ('score_security', models.PositiveSmallIntegerField(default=0)),
                ('score_planning', models.PositiveSmallIntegerField(default=0)),
                ('score_risk', models.PositiveSmallIntegerField(default=0)),
                ('score_discipline', models.PositiveSmallIntegerField(default=0)),
                ('score_learning', models.PositiveSmallIntegerField(default=0)),
                ('answers', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_current', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-completed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FinancialPersonalityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changes', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='otpchallenge',
            name='purpose',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('REGISTRATION_LOGIN', 'Registration or login')], default='LOGIN', max_length=24),
        ),
        migrations.AddIndex(
            model_name='otpchallenge',
            index=models.Index(fields=['phone', 'purpose', '-created_at'], name='accounts_ot_phone_ac7ee9_idx'),
        ),
        migrations.AddField(
            model_name='financialpersonalityassessment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_personality_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialpersonalityauditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_personality_audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialpersonalityauditlog',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='accounts.financialpersonalityassessment'),
        ),
        migrations.AddIndex(
            model_name='financialpersonalityassessment',
            index=models.Index(fields=['user', '-completed_at'], name='accounts_fi_user_id_299678_idx'),
        ),
        migrations.AddConstraint(
            model_name='financialpersonalityassessment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('user',), name='one_current_financial_personality_per_user'),
        ),
    ]
