# Generated by Django 6.0.7 on 2026-09-04 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_financialpersonalityassessment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmContactSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_ulid', models.CharField(blank=True, max_length=64)),
                ('phone_e164', models.CharField(blank=True, db_index=True, max_length=20)),
                ('payload_hash', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed'), ('needs_review', 'Needs review')], default='pending', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('last_response_code', models.CharField(blank=True, max_length=30)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_contact_sync', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['status', 'next_retry_at'], name='accounts_cr_status_c323c6_idx')],
            },
        ),
    ]
