# Generated by Django 6.0.7 on 2026-09-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_crmcontactsync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmcontactsync',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed'), ('needs_review', 'Needs review'), ('dead_letter', 'Dead letter')], default='pending', max_length=20),
        ),
    ]
