# Generated by Django 6.0.7 on 2026-09-05 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_crmcontactsync_status'),
        ('wallet', '0006_upgradeplan_plan_type_upgradeplan_price_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgraderequest',
            name='price_snapshot_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='upgraderequest',
            name='purchase_idempotency_key',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='upgraderequest',
            name='usd_ledger_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='premium_upgrade_requests', to='wallet.usdledgerentry'),
        ),
        migrations.AddConstraint(
            model_name='upgraderequest',
            constraint=models.UniqueConstraint(condition=models.Q(('purchase_idempotency_key__isnull', False)), fields=('user', 'purchase_idempotency_key'), name='unique_premium_purchase_key_per_user'),
        ),
    ]
