# Generated by Django 6.0.7 on 2026-08-01 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_main_landing_page(apps, schema_editor):
    LandingPage = apps.get_model('landing', 'LandingPage')
    LandingPage.objects.get_or_create(site_key='main')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_key', models.SlugField(default='main', max_length=80, unique=True)),
                ('site_name', models.CharField(blank=True, max_length=150)),
                ('page_title', models.CharField(blank=True, max_length=250)),
                ('meta_title', models.CharField(blank=True, max_length=250)),
                ('meta_description', models.TextField(blank=True)),
                ('canonical_url', models.URLField(blank=True, max_length=500)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='landing/branding/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='landing/branding/')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='landing/seo/')),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=30)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('extra_settings', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['site_key'],
            },
        ),
        migrations.CreateModel(
            name='LandingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=120)),
                ('section_type', models.CharField(choices=[('HERO', 'Hero'), ('FEATURES', 'Features'), ('STATS', 'Statistics'), ('ABOUT', 'About'), ('CTA', 'Call to action'), ('FAQ', 'FAQ'), ('TESTIMONIALS', 'Testimonials'), ('PARTNERS', 'Partners'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=30)),
                ('title', models.CharField(blank=True, max_length=250)),
                ('subtitle', models.TextField(blank=True)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('image', models.ImageField(blank=True, null=True, upload_to='landing/sections/')),
                ('cta_label', models.CharField(blank=True, max_length=120)),
                ('cta_url', models.CharField(blank=True, max_length=500)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_landing_sections', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='landing.landingpage')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'indexes': [models.Index(fields=['page', 'is_active', 'display_order'], name='landing_lan_page_id_6fb1a2_idx')],
                'constraints': [models.UniqueConstraint(fields=('page', 'key'), name='unique_landing_section_key_per_page')],
            },
        ),
        migrations.RunPython(
            create_main_landing_page,
            migrations.RunPython.noop,
        ),
    ]
