# Generated by Django 6.0.7 on 2026-07-18 07:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=180, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brokers/')),
                ('website_url', models.URLField(max_length=500)),
                ('registration_url', models.URLField(blank=True, max_length=500)),
                ('support_url', models.URLField(blank=True, max_length=500)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('regulation', models.CharField(blank=True, max_length=250)),
                ('minimum_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('rating', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('5'))])),
                ('features', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', '-rating', 'name'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='brokers_bro_is_acti_bdb497_idx'), models.Index(fields=['country'], name='brokers_bro_country_8eb8b2_idx')],
            },
        ),
    ]
