# Generated by Django 6.0.7 on 2026-08-03 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_channels(apps, schema_editor):
    Channel = apps.get_model("content_channels", "Channel")
    Channel.objects.get_or_create(slug="vip-signals", defaults={"name": "VIP Signals", "min_access_level": 5})
    Channel.objects.get_or_create(slug="internal-analysis", defaults={"name": "Internal Analysis", "min_access_level": 1})


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signals', '0003_signal_closed_at_signal_order_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('min_access_level', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChannelPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='channels/images/%Y/%m/')),
                ('video', models.FileField(blank=True, null=True, upload_to='channels/videos/%Y/%m/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='channels/audio/%Y/%m/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='channels/covers/%Y/%m/')),
                ('scope', models.CharField(blank=True, choices=[('dollar', 'Dollar'), ('gold', 'Gold'), ('stock', 'Stock'), ('housing', 'Housing')], max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='channel_posts', to=settings.AUTH_USER_MODEL)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='content_channels.channel')),
                ('signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_posts', to='signals.signal')),
            ],
            options={
                'ordering': ['-is_pinned', '-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ChannelMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='content_channels.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('channel', 'user'), name='unique_channel_membership')],
            },
        ),
        migrations.RunPython(create_default_channels, migrations.RunPython.noop),
    ]
