# Generated by Django 6.0.7 on 2026-08-14 11:08

import apps.content_channels.models
from django.db import migrations, models


def normalize_scope_values(apps, schema_editor):
    ChannelPost = apps.get_model("content_channels", "ChannelPost")
    for old, new in {
        "dollar": "DOLLAR", "gold": "GOLD", "stock": "STOCK", "housing": "HOUSING"
    }.items():
        ChannelPost.objects.filter(scope=old).update(scope=new)


class Migration(migrations.Migration):

    dependencies = [
        ('content_channels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelpost',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('SCHEDULED', 'زمان\u200cبندی\u200cشده'), ('PUBLISHED', 'منتشرشده')], db_index=True, default='PUBLISHED', max_length=20),
        ),
        migrations.AddField(
            model_name='channelpost',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='channelpost',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=apps.content_channels.models.secure_channel_upload),
        ),
        migrations.AlterField(
            model_name='channelpost',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=apps.content_channels.models.secure_channel_upload),
        ),
        migrations.AlterField(
            model_name='channelpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.content_channels.models.secure_channel_upload),
        ),
        migrations.AlterField(
            model_name='channelpost',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='channelpost',
            name='scope',
            field=models.CharField(blank=True, choices=[('DOLLAR', 'دلار'), ('GOLD', 'طلا'), ('STOCK', 'بورس'), ('HOUSING', 'مسکن')], max_length=20),
        ),
        migrations.AlterField(
            model_name='channelpost',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=apps.content_channels.models.secure_channel_upload),
        ),
        migrations.RunPython(normalize_scope_values, migrations.RunPython.noop),
    ]
