# Generated by Django 6.0.7 on 2026-08-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=150, unique=True)),
                ('datetime', models.DateTimeField(db_index=True)),
                ('currency', models.CharField(db_index=True, max_length=10)),
                ('impact', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('actual', models.CharField(blank=True, max_length=50)),
                ('forecast', models.CharField(blank=True, max_length=50)),
                ('previous', models.CharField(blank=True, max_length=50)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('source_timestamp', models.DateTimeField()),
                ('source', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['datetime', 'id'],
            },
        ),
    ]
