# Generated by Django 6.0.7 on 2026-08-08 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('feed_url', models.URLField(max_length=500, unique=True)),
                ('language', models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], db_index=True, max_length=2)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('syndication_allowed', models.BooleanField(default=False, help_text='Confirm that this source permits headline/summary syndication.')),
                ('terms_url', models.URLField(blank=True, max_length=500)),
                ('fetch_interval_minutes', models.PositiveSmallIntegerField(default=5)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['language', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.CharField(max_length=64, unique=True)),
                ('guid', models.CharField(blank=True, max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField(blank=True)),
                ('url', models.URLField(max_length=1000)),
                ('canonical_url', models.URLField(db_index=True, max_length=1000)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='market.newssource')),
            ],
            options={
                'ordering': ['-published_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('source', 'canonical_url'), name='unique_news_source_canonical_url')],
            },
        ),
    ]
