# Generated by Django 6.0.7 on 2026-08-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_newssource_newsarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoMarketSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=30)),
                ('market_cap_change_24h', models.FloatField()),
                ('volume_24h', models.DecimalField(decimal_places=2, max_digits=30)),
                ('volume_change_24h', models.FloatField()),
                ('btc_dominance', models.FloatField()),
                ('eth_dominance', models.FloatField()),
                ('tether_price_irr', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fear_greed_value', models.PositiveSmallIntegerField()),
                ('source', models.CharField(default='aggregated', max_length=40)),
                ('captured_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-captured_at', '-id'],
            },
        ),
    ]
