# Generated by Django 6.0.7 on 2026-07-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='source_type',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_file',
        ),
        migrations.AlterField(
            model_name='video',
            name='external_url',
            field=models.URLField(max_length=500),
        ),
    ]
