# Generated by Django 6.0.7 on 2026-07-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_remove_video_source_type_remove_video_video_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='allowed_level_1',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='video',
            name='allowed_level_2',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='video',
            name='allowed_level_3',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='video',
            name='allowed_level_4',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='video',
            name='allowed_level_5',
            field=models.BooleanField(default=True),
        ),
    ]
