# Generated by Django 6.0.7 on 2026-08-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_allowed_level_1_video_allowed_level_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='file_size_bytes',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='video',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/files/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='video',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='external_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
