# Generated by Django 6.0.7 on 2026-08-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_coursesession_audio_file_coursesession_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='monthly_session_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='weekly_session_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
