# Generated by Django 6.0.7 on 2026-08-24 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_system_content(apps, schema_editor):
    Content = apps.get_model("platform_settings", "SystemContent")
    rows = [
        ("dashboard-title", "dashboard", "Dashboard title", "داشبورد"),
        ("dashboard-welcome", "dashboard", "Welcome", "به سوکانکس خوش آمدید"),
        ("auth-login-title", "auth", "Login title", "ورود به سوکانکس"),
        ("auth-register-title", "auth", "Register title", "ثبت‌نام در سوکانکس"),
        ("academy-title", "academy", "Academy title", "آکادمی سوکانکس"),
        ("academy-empty", "academy", "Academy empty state", "دوره‌ای برای نمایش وجود ندارد"),
        ("signals-title", "signals", "Signals title", "سیگنال‌ها"),
        ("signals-empty", "signals", "Signals empty state", "سیگنالی وجود ندارد"),
        ("wallet-title", "wallet", "Wallet title", "کیف پول"),
        ("wallet-deposit-cta", "wallet", "Deposit CTA", "افزایش موجودی"),
        ("support-title", "support", "Support title", "پشتیبانی"),
        ("support-empty", "support", "Support empty state", "هنوز پیامی وجود ندارد"),
        ("general-cta", "general", "General CTA", "مشاهده جزئیات"),
    ]
    for key, section, label, value in rows:
        Content.objects.get_or_create(key=key, defaults={"section": section, "label": label, "value": value})


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=160, unique=True)),
                ('section', models.CharField(db_index=True, max_length=60)),
                ('label', models.CharField(max_length=160)),
                ('value', models.TextField(blank=True)),
                ('multiline', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['section', 'key'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Sokanex', max_length=120)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=30)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('minimum_deposit_irt', models.PositiveBigIntegerField(default=10000)),
                ('minimum_withdrawal_irt', models.PositiveBigIntegerField(default=100000)),
                ('maximum_withdrawal_irt', models.PositiveBigIntegerField(default=1000000000)),
                ('withdrawal_fee_irt', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(seed_system_content, migrations.RunPython.noop),
    ]
