# Generated by Django 6.0.7 on 2026-08-30 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_english_catalog(apps, schema_editor):
    catalog = apps.get_model('platform_settings', 'UITranslationCatalog')
    catalog.objects.get_or_create(locale='en', defaults={'translations': {}, 'version': 1})


class Migration(migrations.Migration):

    dependencies = [
        ('platform_settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UITranslationCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(default='en', max_length=12, unique=True)),
                ('translations', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_translation_catalogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['locale'],
            },
        ),
        migrations.CreateModel(
            name='UITranslationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_version', models.PositiveBigIntegerField()),
                ('new_version', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translation_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='platform_settings.uitranslationcatalog')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.RunPython(seed_english_catalog, migrations.RunPython.noop),
    ]
