# Generated by Django 6.0.7 on 2026-08-24 08:49

import django.db.models.deletion
import uuid


def seed_financial_catalog(apps, schema_editor):
    Provider = apps.get_model("wallet", "PaymentProvider")
    Plan = apps.get_model("wallet", "UpgradePlan")
    Provider.objects.get_or_create(code="ZARINPAL", defaults={"title": "زرین‌پال", "sort_order": 1})
    Provider.objects.get_or_create(code="IDPAY", defaults={"title": "آیدی‌پی", "sort_order": 2})
    for level in range(1, 6):
        Plan.objects.get_or_create(level=level, defaults={
            "title": f"سطح {level}", "price_irt": 0 if level == 1 else 0,
            "active": True, "sort_order": level, "features": [],
        })
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(max_length=40)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('ZARINPAL', 'Zarinpal'), ('IDPAY', 'IDPay')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('sandbox', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpgradePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(unique=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('price_irt', models.PositiveBigIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('features', models.JSONField(blank=True, default=list)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'level'],
            },
        ),
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('card_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('iban', models.CharField(blank=True, max_length=26)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_irt', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], default='PENDING', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='wallet.bankcard')),
                ('ledger_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wallet.ledgertransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(db_index=True, max_length=80)),
                ('direction', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=6)),
                ('amount_irt', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='wallet.wallet')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='wallet.ledgertransaction')),
            ],
            options={
                'indexes': [models.Index(fields=['wallet', 'direction', 'created_at'], name='wallet_ledg_wallet__d46c11_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('authority', models.CharField(blank=True, db_index=True, max_length=120)),
                ('provider_reference', models.CharField(blank=True, max_length=120)),
                ('amount_irt', models.PositiveBigIntegerField()),
                ('purpose', models.CharField(choices=[('WALLET_DEPOSIT', 'Wallet deposit'), ('COURSE_PURCHASE', 'Course purchase'), ('LEVEL_UPGRADE', 'Level upgrade')], max_length=30)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=12)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('ledger_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wallet.ledgertransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='wallet.paymentprovider')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'idempotency_key'), name='unique_payment_idempotency_per_user')],
            },
        ),
        migrations.RunPython(seed_financial_catalog, migrations.RunPython.noop),
    ]
