# Generated by Django 6.0.7 on 2026-09-05 05:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def seed_usd_wallets_and_premium_plan(apps, schema_editor):
    Wallet = apps.get_model("wallet", "Wallet")
    UsdLedgerEntry = apps.get_model("wallet", "UsdLedgerEntry")
    UpgradePlan = apps.get_model("wallet", "UpgradePlan")
    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))

    premium = UpgradePlan.objects.filter(level=5).first()
    if premium:
        premium.plan_type = "PREMIUM"
        if premium.price_usd == Decimal("0.00"):
            premium.price_usd = Decimal("100.00")
        premium.save(update_fields=["plan_type", "price_usd"])

    for user_id in User.objects.values_list("pk", flat=True).iterator():
        wallet, _ = Wallet.objects.get_or_create(
            user_id=user_id,
            defaults={"balance_usd": Decimal("100.00")},
        )
        entry, created = UsdLedgerEntry.objects.get_or_create(
            wallet=wallet,
            idempotency_key="WELCOME_CREDIT",
            defaults={
                "direction": "CREDIT",
                "amount_usd": Decimal("100.00"),
                "balance_after": Decimal("100.00"),
                "kind": "WELCOME_CREDIT",
                "description": "Initial Sokanex USD welcome credit",
                "metadata": {},
            },
        )
        if created and wallet.balance_usd != Decimal("100.00"):
            wallet.balance_usd = Decimal("100.00")
            wallet.save(update_fields=["balance_usd"])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0005_upgrade_plan_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgradeplan',
            name='plan_type',
            field=models.CharField(choices=[('UPGRADE', 'Level upgrade'), ('PREMIUM', 'Premium subscription')], default='UPGRADE', max_length=20),
        ),
        migrations.AddField(
            model_name='upgradeplan',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='wallet',
            name='balance_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.CreateModel(
            name='UsdLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=6)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=18)),
                ('kind', models.CharField(db_index=True, max_length=40)),
                ('idempotency_key', models.CharField(blank=True, max_length=160, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usd_ledger_entries', to='wallet.wallet')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('wallet', 'idempotency_key'), name='unique_usd_ledger_idempotency_per_wallet')],
            },
        ),
        migrations.RunPython(seed_usd_wallets_and_premium_plan, migrations.RunPython.noop),
    ]
