from django.urls import path

from .views import (
    BadgeDetailView,
    BadgeListCreateView,
    LogoutView,
    ProfileView,
    ProfileDetailsView,
    AdminUserProfileDetailsView,
    RegisterView,
    ToggleUserStatusView,
    UpdateUserRoleView,
    UpdateUserAccessLevelView,
    MyUpgradeRequestListCreateView,
    UpgradeRequestManagementListView,
    UpgradeRequestReviewView,
    PlatformRoleListCreateView,
    PlatformRoleDetailView,
    UpdateUserCustomRoleView,
    UserListView,
    UserDetailView,
    MyBadgeListView,
    MyDeviceListView,
    RevokeDeviceView,
    RevokeOtherDevicesView,
    SecuritySettingsView,
    UserBadgeDetailView,
    UserBadgeListCreateView,
    OTPRequestView,
    OTPVerifyView,
)


urlpatterns = [
    path("auth/otp/request/", OTPRequestView.as_view(), name="otp-request"),
    path("auth/otp/verify/", OTPVerifyView.as_view(), name="otp-verify"),
    path("devices/", MyDeviceListView.as_view(), name="my-devices"),
    path("devices/logout-others/", RevokeOtherDevicesView.as_view(), name="logout-other-devices"),
    path("devices/<int:pk>/logout/", RevokeDeviceView.as_view(), name="logout-device"),
    path("badges/", BadgeListCreateView.as_view(), name="badge-list-create"),
    path("badges/mine/", MyBadgeListView.as_view(), name="my-badges"),
    path("badges/<str:slug>/", BadgeDetailView.as_view(), name="badge-detail"),
    path("users/<int:pk>/badges/", UserBadgeListCreateView.as_view(), name="user-badges"),
    path("user-badges/<int:pk>/", UserBadgeDetailView.as_view(), name="user-badge-detail"),
    path("security/settings/", SecuritySettingsView.as_view(), name="security-settings"),
    path(
        "profile/",
        ProfileView.as_view(),
        name="profile",
    ),
    path(
        "register/",
        RegisterView.as_view(),
        name="register",
    ),
    path(
        "logout/",
        LogoutView.as_view(),
        name="logout",
    ),
    path(
        "users/",
        UserListView.as_view(),
        name="user-list",
    ),
    path(
        "users/<int:pk>/",
        UserDetailView.as_view(),
        name="user-detail",
    ),
    path(
        "users/<int:pk>/toggle/",
        ToggleUserStatusView.as_view(),
        name="user-status-toggle",
    ),
    path(
        "users/<int:pk>/role/",
        UpdateUserRoleView.as_view(),
        name="user-role-update",
    ),
    path(
        "profile/details/",
        ProfileDetailsView.as_view(),
        name="profile-details",
    ),
    path(
        "users/<int:pk>/access-level/",
        UpdateUserAccessLevelView.as_view(),
        name="user-access-level-update",
    ),
    path(
        "upgrade-requests/",
        MyUpgradeRequestListCreateView.as_view(),
        name="my-upgrade-requests",
    ),
    path(
        "admin/upgrade-requests/",
        UpgradeRequestManagementListView.as_view(),
        name="upgrade-request-management",
    ),
    path(
        "admin/upgrade-requests/<int:pk>/review/",
        UpgradeRequestReviewView.as_view(),
        name="upgrade-request-review",
    ),
    path(
        "roles/",
        PlatformRoleListCreateView.as_view(),
        name="platform-role-list-create",
    ),
    path(
        "roles/<str:slug>/",
        PlatformRoleDetailView.as_view(),
        name="platform-role-detail",
    ),
    path(
        "users/<int:pk>/custom-role/",
        UpdateUserCustomRoleView.as_view(),
        name="user-custom-role-update",
    ),
    path(
        "users/<int:pk>/profile-details/",
        AdminUserProfileDetailsView.as_view(),
        name="admin-user-profile-details",
    ),
]
