from django.urls import path

from .views import (
    LogoutView,
    ProfileView,
    ProfileDetailsView,
    AdminUserProfileDetailsView,
    RegisterView,
    ToggleUserStatusView,
    UpdateUserRoleView,
    UpdateUserAccessLevelView,
    MyUpgradeRequestListCreateView,
    UpgradeRequestManagementListView,
    UpgradeRequestReviewView,
    PlatformRoleListCreateView,
    PlatformRoleDetailView,
    UpdateUserCustomRoleView,
    UserListView,
)


urlpatterns = [
    path(
        "profile/",
        ProfileView.as_view(),
        name="profile",
    ),
    path(
        "register/",
        RegisterView.as_view(),
        name="register",
    ),
    path(
        "logout/",
        LogoutView.as_view(),
        name="logout",
    ),
    path(
        "users/",
        UserListView.as_view(),
        name="user-list",
    ),
    path(
        "users/<int:pk>/toggle/",
        ToggleUserStatusView.as_view(),
        name="user-status-toggle",
    ),
    path(
        "users/<int:pk>/role/",
        UpdateUserRoleView.as_view(),
        name="user-role-update",
    ),
    path(
        "profile/details/",
        ProfileDetailsView.as_view(),
        name="profile-details",
    ),
    path(
        "users/<int:pk>/access-level/",
        UpdateUserAccessLevelView.as_view(),
        name="user-access-level-update",
    ),
    path(
        "upgrade-requests/",
        MyUpgradeRequestListCreateView.as_view(),
        name="my-upgrade-requests",
    ),
    path(
        "admin/upgrade-requests/",
        UpgradeRequestManagementListView.as_view(),
        name="upgrade-request-management",
    ),
    path(
        "admin/upgrade-requests/<int:pk>/review/",
        UpgradeRequestReviewView.as_view(),
        name="upgrade-request-review",
    ),
    path(
        "roles/",
        PlatformRoleListCreateView.as_view(),
        name="platform-role-list-create",
    ),
    path(
        "roles/<str:slug>/",
        PlatformRoleDetailView.as_view(),
        name="platform-role-detail",
    ),
    path(
        "users/<int:pk>/custom-role/",
        UpdateUserCustomRoleView.as_view(),
        name="user-custom-role-update",
    ),
    path(
        "users/<int:pk>/profile-details/",
        AdminUserProfileDetailsView.as_view(),
        name="admin-user-profile-details",
    ),
]
