# Generated by Django 6.0.7 on 2026-07-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='allowed_level_1',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='allowed_level_2',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='allowed_level_3',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='allowed_level_4',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='allowed_level_5',
            field=models.BooleanField(default=True),
        ),
    ]
