# Generated by Django 6.0.7 on 2026-08-03 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import uuid


def populate_signal_ids(apps, schema_editor):
    Signal = apps.get_model("signals", "Signal")
    for signal in Signal.objects.filter(signal_id__isnull=True).iterator():
        signal.signal_id = f"SIG-{uuid.uuid4().hex[:12].upper()}"
        signal.save(update_fields=["signal_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0002_signal_allowed_level_1_signal_allowed_level_2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='order_type',
            field=models.CharField(choices=[('market', 'Market'), ('limit', 'Limit'), ('stop', 'Stop')], default='market', max_length=10),
        ),
        migrations.AddField(
            model_name='signal',
            name='result_percent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='result_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='signal_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.RunPython(populate_signal_ids, migrations.RunPython.noop),
        migrations.AddField(
            model_name='signal',
            name='timeframe',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='signal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('successful', 'Successful'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='SignalUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('successful', 'Successful'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='signals/updates/images/%Y/%m/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='signals/updates/audio/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signal_updates', to=settings.AUTH_USER_MODEL)),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='signals.signal')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
