# Generated by Django 6.0.7 on 2026-08-29 10:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('provider', models.CharField(default='GAPGPT', max_length=30)),
                ('base_url', models.URLField(default='https://api.gapgpt.app/v1')),
                ('api_token_encrypted', models.TextField(blank=True)),
                ('model', models.CharField(blank=True, max_length=150)),
                ('financial_system_prompt', models.TextField(default='به فارسی پاسخ بده و اصول مدیریت ریسک را رعایت کن.')),
                ('technical_system_prompt', models.TextField(default='نمودار را به فارسی و با بیان عدم قطعیت تحلیل کن.')),
                ('temperature', models.FloatField(default=0.3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('max_tokens', models.PositiveIntegerField(default=1200, validators=[django.core.validators.MinValueValidator(128), django.core.validators.MaxValueValidator(8192)])),
                ('daily_user_limit', models.PositiveIntegerField(default=20)),
                ('image_daily_user_limit', models.PositiveIntegerField(default=5)),
                ('request_timeout', models.PositiveSmallIntegerField(default=45, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(120)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AISettingsAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_fields', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ai_settings', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='ai_assistant.aisettings')),
            ],
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('financial', 'Financial chat'), ('technical', 'Technical image')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], db_index=True, max_length=20)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('provider_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'mode', 'created_at'], name='ai_assistan_user_id_2f2393_idx')],
            },
        ),
    ]
