# Generated by Django 6.0.7 on 2026-08-01 08:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='notifications/images/'),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('INFO', 'Information'), ('SIGNAL', 'Signal'), ('ARTICLE', 'Article'), ('VIDEO', 'Video'), ('SYSTEM', 'System'), ('SOCIAL', 'Social'), ('ACADEMY', 'Academy'), ('SECURITY', 'Security')], default='INFO', max_length=20),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_active', 'expires_at', '-created_at'], name='notificatio_is_acti_abb010_idx'),
        ),
    ]
