# Generated by Django 6.0.7 on 2026-08-20 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_action_label_notification_expires_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='allowed_level_1',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='allowed_level_2',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='allowed_level_3',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='allowed_level_4',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='allowed_level_5',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='send_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='NotificationSMSDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=10)),
                ('provider_message_id', models.CharField(blank=True, max_length=100)),
                ('provider_code', models.CharField(blank=True, max_length=50)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_deliveries', to='notifications.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_sms_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'attempts', 'created_at'], name='notificatio_status_40372d_idx')],
                'constraints': [models.UniqueConstraint(fields=('notification', 'user'), name='unique_notification_sms_per_user')],
            },
        ),
    ]
