# Generated by Django 6.0.7 on 2026-08-01 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0002_liveevent_allowed_level_1_liveevent_allowed_level_2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='liveevent',
            name='provider',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('ALOCOM', 'Alocom')], default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='liveevent',
            name='provider_event_id',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='liveevent',
            name='provider_join_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='liveevent',
            name='provider_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='AlocomSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_base_url', models.URLField(default='https://pnlapi.alocom.co')),
                ('api_token_encrypted', models.TextField(blank=True, editable=False)),
                ('enabled', models.BooleanField(default=False)),
                ('request_timeout_seconds', models.PositiveSmallIntegerField(default=20)),
                ('verify_ssl', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alocom_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Alocom settings',
            },
        ),
    ]
