# Generated by Django 6.0.7 on 2026-08-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0006_livechatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveevent',
            name='external_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
