# Generated by Django 6.0.7 on 2026-08-08 21:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0006_livechatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='livechatmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livechatmessage',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_live_chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livechatmessage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='liveevent',
            name='comments_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='liveevent',
            name='max_participants',
            field=models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AddField(
            model_name='liveevent',
            name='recording_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='liveevent',
            name='room_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='liveevent',
            name='viewer_display_offset',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AddField(
            model_name='livepresence',
            name='can_publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livepresence',
            name='removed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removed_live_participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LiveRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('egress_id', models.CharField(max_length=150, unique=True)),
                ('status', models.CharField(choices=[('starting', 'Starting'), ('active', 'Active'), ('ending', 'Ending'), ('complete', 'Complete'), ('failed', 'Failed')], default='starting', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=1000)),
                ('playback_url', models.URLField(blank=True, max_length=1000)),
                ('error', models.CharField(blank=True, max_length=1000)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='livestream.liveevent')),
                ('started_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_live_recordings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
    ]
