# Generated by Django 6.0.7 on 2026-09-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0007_liveevent_external_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveevent',
            name='join_early_minutes',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
