# Generated by Django 6.0.7 on 2026-08-03 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_support_account(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    user, created = User.objects.get_or_create(
        username="support",
        defaults={
            "is_active": True,
            "role": "EMPLOYEE",
            "password": "!support-system-account-no-direct-login",
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_traderpost_savedpost_postreport_postreaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_threads', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='support_thread', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='chat/support/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.supportthread')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.RunPython(create_support_account, migrations.RunPython.noop),
    ]
