# Generated by Django 6.0.7 on 2026-08-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_supportthread_supportmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
