# Generated by Django 6.0.7 on 2026-08-09 16:19

from django.conf import settings
from django.db import migrations, models


def populate_support_metadata(apps, schema_editor):
    SupportThread = apps.get_model("chat", "SupportThread")
    SupportMessage = apps.get_model("chat", "SupportMessage")
    User = apps.get_model("accounts", "User")
    support_user = User.objects.filter(username="support", is_active=True).first()
    SupportMessage.objects.filter(read_at__isnull=False).update(is_read=True)
    for thread in SupportThread.objects.all().iterator():
        last_message = SupportMessage.objects.filter(thread_id=thread.pk).order_by(
            "-created_at", "-id"
        ).first()
        thread.status = "closed" if thread.is_closed else "open"
        thread.closed_at = thread.updated_at if thread.is_closed else None
        thread.last_message_at = last_message.created_at if last_message else None
        if support_user:
            thread.assigned_to_id = support_user.pk
        thread.save(update_fields=[
            "status", "closed_at", "last_message_at", "assigned_to"
        ])


class Migration(migrations.Migration):

    # PostgreSQL cannot create the indexes below in the same transaction as
    # the data migration because the updates leave pending trigger events.
    atomic = False

    dependencies = [
        ('chat', '0004_supportmessage_delivered_at_supportmessage_read_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportthread',
            options={'ordering': ['-last_message_at', '-updated_at']},
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='supportthread',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportthread',
            name='last_message_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='supportthread',
            name='priority',
            field=models.CharField(choices=[('low', 'کم'), ('normal', 'عادی'), ('high', 'زیاد'), ('urgent', 'فوری')], default='normal', max_length=12),
        ),
        migrations.AddField(
            model_name='supportthread',
            name='status',
            field=models.CharField(choices=[('open', 'در حال پیگیری'), ('pending', 'در انتظار پاسخ'), ('closed', 'بسته شده')], default='open', max_length=12),
        ),
        migrations.AddField(
            model_name='supportthread',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(populate_support_metadata, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['thread', 'is_read'], name='chat_suppor_thread__e2a1c9_idx'),
        ),
        migrations.AddIndex(
            model_name='supportthread',
            index=models.Index(fields=['status', 'last_message_at'], name='chat_suppor_status_fd8d15_idx'),
        ),
    ]
