# Generated by Django 6.0.7 on 2026-08-24 08:51

from django.conf import settings
from django.db import migrations, models


def assign_support_role(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(username__iexact="support").update(
        role="SUPPORT", is_staff=False, is_superuser=False
    )


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_supportthread_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddConstraint(
            model_name='supportmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('thread', 'sender', 'idempotency_key'), name='unique_support_message_idempotency'),
        ),
        migrations.RunPython(assign_support_role, migrations.RunPython.noop),
    ]
